### ISSUE TITLE
Remove singleton pattern from RMIStoppingCondition

### ISSUE THREAD

**Issue by VoglSebastian** [VoglSebastian/evosuite#23]
Currently RMIStoppingCondition is a singleton with following getInstance() function:

```
@SuppressWarnings("unchecked")
public static <T extends Chromosome<T>> RMIStoppingCondition<T> getInstance() {
	if (instance == null)
		instance = new RMIStoppingCondition<>();
	return (RMIStoppingCondition<T>) instance;
}
```

This breaks if T is not always the same for all calls to getInstance() (due to the cast at the end), isn't it?
e.g.
`RMIStoppingCondition<TestSuiteChromosome> = RMIStoppingCondition.getInstance();
// ...
RMIStoppingCondition<TestChromosome> = RMIStoppingCondition.getInstance();`

I am concerned about following line:
https://github.com/VoglSebastian/evosuite/blob/612eef35768cd7fa7672b779136f11cfcbf97368/client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java#L484

It looks, that the singleton pattern is no applicable.

I have thought of 2 possible solutions:

1. Make RMIStoppingCondition abstract and create a subclass for each Chromosome type (with Singleton pattern).
2. Remove Singleton pattern and make the Field RMIStoppingCondition.isStopped static.

Any thoughts on this subject?

**Comment by schweikl** [comment]
> This breaks if T is not always the same for all calls to getInstance() (due to the cast at the end), isn't it?

I see your point, but I'm not sure if this is a problem in our case. As long as `RMIStoppingCondition` doesn't actually do anything with a `T` instance it should be fine. Running EvoSuite using the code from the `16-fix-or-remove-broken-local-search` branch works for me. (You cannot use the `selfType` branch right now because there the methods related to bloat control are not implemented yet, so the program fails before a stopping condition is even added.) I used the command line parameters
```
-Dalgorithm=MIO -Dstrategy=MOSuite -generateMOSuite -Dlocal_search_rate=1 -Dclient_on_thread=true
```
A break point set on this line
https://github.com/VoglSebastian/evosuite/blob/612eef35768cd7fa7672b779136f11cfcbf97368/client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java#L484
is triggered (so we know the line is executed) and the execution does not cause a casting error for me; here, `RMIStoppingCondition<TestSuiteChromosome>` is cast to `RMIStoppingCondition<TestChromosome>`.

Do you have an example where this casting operation fails?

**Comment by schweikl** [comment]
But maybe we could/should add a comment to the implementation
```Java
@SuppressWarnings("unchecked")
public static <T extends Chromosome<T>> RMIStoppingCondition<T> getInstance() {
	if (instance == null)
		instance = new RMIStoppingCondition<>();
	return (RMIStoppingCondition<T>) instance;
}
```
that explains why the cast succeeds.

**Comment by schweikl** [comment]
I have added a comment to `getInstance()` explaining why this unchecked cast always succeeds (519f521c1). This closes the issue for me. If we find that this cast does indeed cause some problems, we can always reopen this issue later.
